import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "./providers";
import NavbarView from "@/components/navbar/horizontalNav/navbar";
import { ReduxProvider } from "../store/provider";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import LayoutWrapper from "./layoutWrapper";
import { getAuth } from "./hooks/useAuth";
import AuthProvider from "./providers/authProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Agrimarket",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
const { role } = await getAuth();

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} antialiased dark`}
    >
      <body>
        <UserProvider>
          <ReduxProvider>
            <ThemeProvider>
              <AuthProvider />
              <NavbarView />
              <LayoutWrapper role={role} >{children}</LayoutWrapper>
            </ThemeProvider>
          </ReduxProvider>
        </UserProvider>
      </body>
    </html>
  );
}
